name: test action
on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: deweya/chart-repo-pr-action@feat/parameters
        with:
          token: ${{ secrets.PAT }}
          fork_name: deweya/helm-charts
          upstream_owner: deweya0